### ISSUE TITLE
拉取代码编译成功, 但是进入"更好买"与"工作面板"失败

### ISSUE THREAD

**Issue by FairyOwO** [LorisYounger/VPet#408]
<details><summary>进入更好买的报错</summary>
<p>

![image](https://github.com/user-attachments/assets/d130a997-3510-452a-a65c-1d2673c5b2d2)

</p>
</details> 

<details><summary>进入工作面板的报错(三个)</summary>
<p>

System.NullReferenceException: Object reference not set to an instance of an object.
   at VPet_Simulator.Windows.winWorkMenu.<>c__DisplayClass9_0.<ShowImageDefault>b__0() in C:\Users\DELL\Desktop\code\VPet\VPet-Simulator.Windows\WinDesign\winWorkMenu.xaml.cs:line 39
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.NullReferenceException: Object reference not set to an instance of an object.
   at VPet_Simulator.Windows.winWorkMenu.ShowImageDefault(WorkType type) in C:\Users\DELL\Desktop\code\VPet\VPet-Simulator.Windows\WinDesign\winWorkMenu.xaml.cs:line 42
   at VPet_Simulator.Windows.winWorkMenu.<LsbCategory_SelectionChanged>b__18_0() in C:\Users\DELL\Desktop\code\VPet\VPet-Simulator.Windows\WinDesign\winWorkMenu.xaml.cs:line 189
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.Windows.Markup.XamlParseException: 在“System.Windows.Markup.StaticExtension”上提供值时引发了异常。
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Panuon.WPF.UI.Resources.Converters' threw an exception.
 ---> System.MissingFieldException: Field not found: 'Panuon.WPF.Resources.Converters.AutoCornerRadiusConverter'.
   at Panuon.WPF.UI.Resources.Converters..cctor()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.RuntimeFieldHandle.GetValue(RtFieldInfo field, Object instance, RuntimeType fieldType, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at VPet_Simulator.Windows.winWorkMenu.InitializeComponent() in C:\Users\DELL\Desktop\code\VPet\VPet-Simulator.Windows\WinDesign\winWorkMenu.xaml:line 1
   at VPet_Simulator.Windows.winWorkMenu..ctor(MainWindow mw, WorkType type) in C:\Users\DELL\Desktop\code\VPet\VPet-Simulator.Windows\WinDesign\winWorkMenu.xaml.cs:line 48
   at VPet_Simulator.Windows.MainWindow.ShowWorkMenu(WorkType type) in C:\Users\DELL\Desktop\code\VPet\VPet-Simulator.Windows\MainWindow.cs:line 433
   at VPet_Simulator.Windows.MainWindow.<>c__DisplayClass70_0.<GameLoad>b__15(Object x, RoutedEventArgs y) in C:\Users\DELL\Desktop\code\VPet\VPet-Simulator.Windows\MainWindow.cs:line 1653
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

</p>
</details> 

将代码回滚到commit id为 `e257aa4d` 之前再进行编译无问题, 疑似是更新NUGET中的几个包版本产生的问题

**Comment by LorisYounger** [comment]
e257aa4d 和 e5b0e34 的区别只有更新了翻译, 怪

**Comment by LorisYounger** [comment]
`Panuon.WPF` 从 `1.1.2.1` 滚回到 `1.1.0.1` 就好了, 还真是包更新的问题, 已经让PUI作者去看看咋回事

**Comment by LorisYounger** [comment]
和UI作者对接了, 他说不小心传错版本了, 已经更新为正确的版本
