### ISSUE TITLE
购买礼物"GTC4090"时程序报错

### ISSUE THREAD

**Issue by hehe-minecraft** [LorisYounger/VPet#413]
# 描述
购买礼物"GTC4090"时，程序抛出了空引用（`NullReferenceException`）异常。其他礼物没有这个问题。这个问题不由其他模组导致。
# 复现
只需要给桌宠购买"GTC4090"就可以复现问题。
具体过程如下：

https://github.com/user-attachments/assets/3c581cfa-094c-48f0-b822-b4be987f25f2
# 报错消息
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at VPet_Simulator.Windows.Interface.GameSave_VPet.set_Exp(Double value)
   at VPet_Simulator.Windows.Interface.ExtensionFunction.EatFood(IGameSave save, IFood food, Double buff)
   at VPet_Simulator.Windows.MainWindow.TakeItem(Food item) in D:\Documents\Visual Studio 2022\Projects\VPet\VPet-Simulator.Windows\MainWindow.cs:line 640
   at VPet_Simulator.Windows.winBetterBuy.BtnBuy_Click(Object sender, RoutedEventArgs e) in D:\Documents\Visual Studio 2022\Projects\VPet\VPet-Simulator.Windows\WinDesign\winBetterBuy.xaml.cs:line 237
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
# 存档数据
[Save.txt](https://github.com/user-attachments/files/16606304/Save.txt)
由于 GitHub 无法上传 .lps 文件，故将其更改为 .txt 文件上传。

**Comment by CCCCCCHARA** [comment]
问题参考 #414

**Comment by LorisYounger** [comment]
已修复, 请验证Steam完整性后 重试看看有没有问题?
