### ISSUE TITLE
[BUG] Cloud Save - Opening MOD settings

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#416]
Hey there!
I have installed the MOD Cloud Save and enabled it. After a fresh start of the game i got this error message while trying to open the MOD settings.
The error happens everytime.

---------------------------
Error:CloudSaves
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at VPet.Plugin.CloudSaves.winSetting..ctor(CloudSave CS) in D:\Documents\Visual Studio 2022\Projects\VPet.Plugin.Demo\VPet.Plugin.CloudSaves\winSetting.xaml.cs:line 32

   at VPet.Plugin.CloudSaves.CloudSave.Setting() in D:\Documents\Visual Studio 2022\Projects\VPet.Plugin.Demo\VPet.Plugin.CloudSaves\CloudSave.cs:line 74

   at VPet_Simulator.Windows.winGameSetting.ButtonSetting_MouseDown(Object sender, MouseButtonEventArgs e) in D:\Documents\Visual Studio 2022\Projects\VPet\VPet-Simulator.Windows\WinDesign\winGameSetting.xaml.cs:line 1215

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![grafik](https://github.com/user-attachments/assets/0b61dcb8-34ac-4110-972c-8d16030c0832)

**Comment by LorisYounger** [comment]
Fixed in https://github.com/LorisYounger/VPet.Plugin.Demo/tree/main/VPet.Plugin.CloudSaves
