### ISSUE TITLE
Error while selecting next page in photo gallery [BUG]

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#431]
Hello there!
I have noticed a bug inside the photo gallery.

### 
Can be reproduced like this (only once per game run):
1. Fresh start the game
2. Open the photo gallery
3. Click on Filter "Locked" (active now)
4. Navigate to last page with ">" from the page selector (the error can appear at this step already too)
5. Click on filter "Locked" (inactive now)
6. Click on filter "Locked" (active now)
7.  Navigate to last page with ">" from the page selector

=== ERROR === 

An error occurred in the game, probablyGame or ModIf possible, Please send a screenshot of the error message and the action you took before triggering the error to developer: service@exlb.net
Thanks for your support of the game development
System.ArgumentOutOfRangeException: Der Parameterwert muss größer Null sein. (Parameter 'pixelWidth')
   at System.Windows.Media.Imaging.RenderTargetBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat)
   at VPet_Simulator.Windows.Interface.Photo.ConvertToThumbnail(BitmapImage originalImage, Int32 width, Int32 height)
   at VPet_Simulator.Windows.WinDesign.Gallery.LockedGalleryItemUc.this_Loaded(Object sender, RoutedEventArgs e) in D:\Documents\Visual Studio 2022\Projects\VPet\VPet-Simulator.Windows\WinDesign\Gallery\LockedGalleryItemUc.xaml.cs:line 86
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Mochengvia** [comment]
bug has been fixed at
https://github.com/LorisYounger/VPet/pull/433
@LorisYounger
